/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { CallCode, CallCodeInterface } from "../CallCode";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "age",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "receiver",
        type: "address",
      },
      {
        name: "_age",
        type: "uint256",
      },
    ],
    name: "testCallCode",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061029a806100206000396000f30060806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063262a9dff14610051578063d4c80cc41461007c575b600080fd5b34801561005d57600080fd5b506100666100c9565b6040518082815260200191505060405180910390f35b34801561008857600080fd5b506100c7600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506100cf565b005b60005481565b60008273ffffffffffffffffffffffffffffffffffffffff1660405180807f7365744167652875696e74323536290000000000000000000000000000000000815250600f01905060405180910390208360405160200180837bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19167bffffffffffffffffffffffffffffffffffffffffffffffffffffffff191681526004018281526020019250505060405160208183030381529060405260405180828051906020019080838360005b838110156101b0578082015181840152602081019050610195565b50505050905090810190601f1680156101dd5780820380516001836020036101000a031916815260200191505b509150506000604051808303816000865af29150509050801515610269576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252600b8152602001807f45727243616c6c436f646500000000000000000000000000000000000000000081525060200191505060405180910390fd5b5050505600a165627a7a723058201369dc106ed37e2a134bd1310ebf21687e89b8cd37641d4e4ceb6326495428ab0029";

export class CallCode__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CallCode> {
    return super.deploy(overrides || {}) as Promise<CallCode>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CallCode {
    return super.attach(address) as CallCode;
  }
  connect(signer: Signer): CallCode__factory {
    return super.connect(signer) as CallCode__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CallCodeInterface {
    return new utils.Interface(_abi) as CallCodeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CallCode {
    return new Contract(address, _abi, signerOrProvider) as CallCode;
  }
}
