/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AddressList",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressList__factory>;
    getContractFactory(
      name: "CallCode",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CallCode__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "GreeterSub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GreeterSub__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "OnChainDao",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnChainDao__factory>;
    getContractFactory(
      name: "USDT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.USDT__factory>;

    getContractAt(
      name: "AddressList",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressList>;
    getContractAt(
      name: "CallCode",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CallCode>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "GreeterSub",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GreeterSub>;
    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "OnChainDao",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OnChainDao>;
    getContractAt(
      name: "USDT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.USDT>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
